DATA_DESCRIPTION_FILE = '/mnt/nfs/projects/hackathon_gem_Adam/data/filenames+labels.csv'
IMAGE_PATH = '/mnt/nfs/projects/hackathon_gem_Adam/data/all_photos/'
INPUT_SIZE = [114, 152] # height, width
COMMON_RATIO = 1.34
CLASS_COUNT = 2
DEFAULT_CACHE_FILE_PATH = '/mnt/nfs/projects/hackathon_gem_Adam/data/cache_just_clean.pickle'
IMAGE_PREPROCESSING_BATCH_COUNT = 40
MULTI_CORE_COUNT = 40
RESULTS_FILEPATH = '/mnt/nfs/projects/hackathon_gem_Adam/data/results.pickle'
