DATA_DESCRIPTION_FILE = './data/filenames+labels.csv'
IMAGE_PATH = '/mnt/nfs/projects/hackathon_gem_Adam/data/hackathon/all_photos/'
INPUT_SIZE = [114, 152] # height, width
COMMON_RATIO = 1.34
CLASS_COUNT = 2
DEFAULT_CACHE_FILE_PATH = '/mnt/nfs/projects/hackathon_gem_Adam/data/multi_label.pickle'
IMAGE_PREPROCESSING_BATCH_COUNT = 15
MULTI_CORE_COUNT = 140
RESULTS_FILEPATH = '/mnt/nfs/projects/hackathon_gem_Adam/data/results.pickle'
TIMEOUT_SECS = 3000.0
CHUNK_SIZE = 10